apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: monolito-healt
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8000
        requestPath: /api/ambassador/health_check
  targetRef:
    group: ""
    kind: Service
    name: monolito